### ISSUE TITLE
[Feature] Firebase database, storage Linking

### ISSUE THREAD

**Issue by KimKwon** [Dagather/Dagather-Web#11]
# Firebase Linking

## 스토리지 요구사항
- [x] 로봇 스크립트 CRUD 기능

## 데이터베이스 요구사항
- [x] 게시글 CRUD 기능
  - [x] 게시글별 유니크 식별 번호 

1. 게시글 제목
2. 게시글 내용
3. 게시글 작성자
4. 작성 일자 ( not fix )
5. 파일 첨부 시 스토리지 파일 path를 통한 접근 및 다운로드 가능

---

## NoSql 설계

데이터 모델링 뒤, 설계 작업하면서 진행도 이슈 작성하겠습니다.

- [x] 도메인모델 파악
- [x] 쿼리 결과 디자인
- [x] 데이터 모델링
- [x] 프론트 연동/링크

**Comment by ggjae** [comment]
도메인 모델을 어떻게 파악하셨나요 ? 정말 똑똑하시네 . . . ㅎㅎ ♡

**Comment by KimKwon** [comment]
> 도메인 모델을 어떻게 파악하셨나요 ? 정말 똑똑하시네 . . . ㅎㅎ ♡

막상 해보니까 도메인 자체가 별로 없었..다는
