### ISSUE TITLE
encrypt-decrypt-password.js 궁금한 점

### ISSUE THREAD

**Issue by ggjae** [Dagather/Dagather-Web#15]
```javascript
import CryptoJS from 'crypto-js';

const pwdEncrypt = (pwd, originSalt, originIv) => {
  const salt = originSalt || CryptoJS.lib.WordArray.random(128 / 8).toString(CryptoJS.enc.Hex);
  const iv = originIv || CryptoJS.lib.WordArray.random(128 / 8).toString(CryptoJS.enc.Hex);

  const iterations = 10000;

  const key512Bits10000Iterations = CryptoJS.PBKDF2('1234', CryptoJS.enc.Hex.parse(salt), {
    keySize: 512 / 32,
    iterations,
  });

  const encrypted = CryptoJS.AES.encrypt(
    pwd,
    key512Bits10000Iterations,
    { iv: CryptoJS.enc.Hex.parse(iv) },
  );

  return {
    encryptedPwd: encrypted.toString(),
    salt,
    iv,
  };
};

export default pwdEncrypt;
```
이 코드 중 
```javascript
const key512Bits10000Iterations = CryptoJS.PBKDF2('1234', CryptoJS.enc.Hex.parse(salt), {
    keySize: 512 / 32,
    iterations,
  });
``` 

부분에서의 PBKDF2('1234') '1234'는 가리지 않아도 되나요? 어떤 용도로 있는 값인지 궁금하네요.

**Comment by ggjae** [comment]
@KimKwon 선생님!

**Comment by KimKwon** [comment]
https://nukw0n-dev.tistory.com/12

이 코드 작성하면서 같이 작성한 포스트인데 참고하시면 좋을 것 같아요.

`PBKDF2` 는 패스워드로부터 driven된 키를 생성하는 알고리즘입니다.
 1234로부터 생성된 키로 유저의 패스워드를 암호화하는 방식이라고 생각하시면 돼요.

아 결과적으로는 1234는 임시로 넣어놓은 값이고 추후에는 환경변수로 처리할까 생각중입니다

**Comment by ggjae** [comment]
> https://nukw0n-dev.tistory.com/12
> 
> 이 코드 작성하면서 같이 작성한 포스트인데 참고하시면 좋을 것 같아요.
> 
> `PBKDF2` 는 패스워드로부터 driven된 키를 생성하는 알고리즘입니다.
> 1234로부터 생성된 키로 유저의 패스워드를 암호화하는 방식이라고 생각하시면 돼요.
> 
> 아 결과적으로는 1234는 임시로 넣어놓은 값이고 추후에는 환경변수로 처리할까 생각중입니다

좋은 글 잘 읽었습니다. MITM은 알아도 레인보우 공격같은 건 처음 들어봤는데 재미있네요.
