### ISSUE TITLE
webpack issue ㅡㅡ

### ISSUE THREAD

**Issue by ggjae** [Dagather/Dagather-Web#16]
![image](https://user-images.githubusercontent.com/22047551/117624618-0fa89900-b1b0-11eb-972f-cab0f58228a5.png)
화가 나요..

**Comment by jekyun-park** [comment]
아래 1~4 번 해보셨나요 ?

**Comment by ggjae** [comment]
> 아래 1~4 번 해보셨나요 ?

네.. 한 일곱번 해보았는데도 웹팩 오류가 안지워지더라구요...... 흑흑.........  
일단 5월 14일이나 15일에 화면공유로 진행상황보고 이야기할 것 좀 나눠봐요!

**Comment by ggjae** [comment]
해결 완료!
